[env:ttgo_t_display]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Memory settings
board_build.flash_mode = dio
board_build.flash_size = 4MB

lib_deps =
    TFT_eSPI
    TJpg_Decoder
    WiFi
    HTTPClient
    ; Built-in ESP32 libraries

build_flags =
    -DCORE_DEBUG_LEVEL=3
