[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

upload_port = COM9
monitor_port = COM9

monitor_speed = 115200
upload_speed = 115200

monitor_rts = 0
monitor_dtr = 0

monitor_filters = direct

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCAMERA_MODEL_AI_THINKER
